on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/stage.vesta.org.ua/
            git pull
            composer install
            wget --no-check-certificate --quiet --method GET --timeout=0 --header '' 'https://tsukr.tech/db_data_migrate.php'
            mysql -u ${{ secrets.DB_USERNAME }} -p ${{ secrets.DB_PASSWORD }} ${{ secrets.DB_DATABASE }} < /var/www/db_storage/prod.sql

            sudo chown -R www-data /var/www/stage.vesta.org.ua
          host: 31.131.17.142
          user: git
          key: ${{ secrets.GITKEY }}
