on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: fifsky/ssh-action@master
        with:
          command: |
            cd /var/www/stage.vesta.org.ua/
            sudo rm -rf *
            git clone https://github.com/kionlife/vesta_2.0.git --branch dev
            cd vesta_2.0 && mv -v * /var/www/stage.vesta.org.ua/
            cd ..
            mkdir storage
            cd storage/
            mkdir -p framework/{sessions,views,cache}
            chown -R www-data:www-data framework
            cd ..
            composer install
            cp /var/www/env_storage/back/dev.env /var/www/stage.vesta.org.ua/.env
            php artisan key:generate
            php artisan passport:install
            php artisan storage:link
            php artisan config:clear
            wget --no-check-certificate --quiet --method GET --timeout=0 --header '' 'https://tsukr.tech/db_data_migrate.php'
            php artisan db:seed --force
            chown -R www-data /var/www/stage.vesta.org.ua
          host: 31.131.17.142
          user: git
          key: ${{ secrets.GITKEY }}
