name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: fifsky/ssh-action@master
      with:
        command: |
          cd /var/www/dev.vesta.org.ua/
          sudo git pull
          sudo composer install
          sudo php artisan migrate:fresh
          sudo php artisan db:seed --class=ServicesTableSeeder
          sudo php artisan db:seed --class=UsersTableSeeder
          sudo php artisan db:seed --class=PermissionsTableSeeder
          sudo php artisan db:seed --class=RolesTableSeeder
          sudo php artisan db:seed --force
          sudo chown -R www-data:groupgit /var/www/dev.vesta.org.ua
        host: 31.131.17.142
        user: git
        key: ${{ secrets.GITKEY }}
